
FROM ubuntu:latest

# Instalacja wymaganych narzędzi
RUN apt-get update && apt-get install -y \
    git \
    npm \
    nodejs

# Instalacja narzędzia jest globalnie
RUN npm install -g jest

# Ustawienie katalogu roboczego
WORKDIR /app

# Klonowanie repozytorium
RUN git clone https://github.com/dsumitro/tic-tac-toe-testing .

# Instalacja zależności
RUN npm install
