FROM ubuntu:latest

# Instaluje narzędzie jest globalnie
RUN npm install -g jest

# Ustawia katalog roboczy na /app
WORKDIR /app

# Klonuje repozytorium
RUN git clone https://github.com/dsumitro/tic-tac-toe-testing .

# Instaluje zależności
RUN npm install
	
# Uruchamia testy
CMD ["npm", "test"]
